//This example file is for demonstration purpose only. Users must not use this keyfile to encrypt their sources. 
//It is strongly recommonded that users create their own key file to use for encrypting their sources. 
`pragma protect begin_protected
`pragma protect version = 2
`pragma protect encrypt_agent = "XILINX"
`pragma protect encrypt_agent_info = "Xilinx Encryption Tool 2022.1"
`pragma protect begin_commonblock
`pragma protect control error_handling = "delegated"
`pragma protect control runtime_visibility = "delegated"
`pragma protect control child_visibility = "delegated"
`pragma protect end_commonblock
`pragma protect begin_toolblock
`pragma protect rights_digest_method="sha256"
`pragma protect key_keyowner = "Xilinx", key_keyname= "xilinxt_2021_07", key_method = "rsa", key_block
Qae/U349HupfZgLKRupdshUsAVO3x1HhNBGj1D1VzeUNS7hvL6WwvFkkMqdUMmVLlt0/nLd6foRB
opUShAlpra51jttCFX9nKJ/QiyUH2dXvv0HM5yzt5TItB3MeaiFqG+XluPLtn7I29O5CZqqGZKSb
gJU0c/qjV4+R5sSUAlUQfaLSt7LJnHn6Or+K1AedPV4MRtROIElP5LlZoZaEITibZxYQbVgpOCY3
RLj7UD8a4EvTdoYn6fmbjSQ5YvCdgMAYrp1tC/JZWXQX7/vewPqTEhhYDCBWLtxwU1p11QbzNBBI
Z0HfZgO2RqtfDlQAEH3NiresTBKgm+ByhDKCZg==

`pragma protect control xilinx_configuration_visible = "true"
`pragma protect control xilinx_enable_modification = "true"
`pragma protect control xilinx_enable_probing = "true"
`pragma protect control xilinx_enable_netlist_export = "true"
`pragma protect control xilinx_enable_bitstream = "true"
`pragma protect control xilinx_schematic_visibility="true"
`pragma protect end_toolblock="ugr54Sj+7RvfSRbZH5iu+dbDY/tcsnvOPqJ1OrrKAI8="
`pragma protect data_method = "AES128-CBC"
`pragma protect encoding = (enctype = "BASE64", line_length = 76, bytes = 1552)
`pragma protect data_block
TvMOxPjuxYh6LgBaGeLpng3Ih0hrYoPZb5LRgszJqbzmQ6aljdB6OOXH7c9rqhjVFbCiAjYQ3TcM
fsBvz80BqQ7g0btltGekukntAVLQliemj5W2w7QK8RZokfnNBe5Ga+t9NDqOuXxEdS4yGU8u8Yuw
TRbAfT6nK4s2zXRw5uqpmQzqUiwUEydQA58ZKUMQqBdhpOuVAOLFwkUBNpxrwamd07b2OzwxYOk1
HcVmtC5JnAJICtbBXkkJgAFDGLZssiTn2/vHiCjQiDHyQalJRXUZIsS/Ercm1ARYdnuByZWymcZN
NQsb0BltRl8aG1jCUuQxaIr24w36NH02EXchH08tsoDnWCQhXwzPwAoh3ARGBAVD5BkXDye3LLVd
LruLucw5MRs6G7okND2pDNiSWx7ROAfTgeJwyg9hd1L8vcGsclzHWKLhGLLiJIvrFy6t7F07pG8g
5W4oTtjbsTStoqpJyDZV5BWAnFzvUNpchfPJ5McVQ1H7eN1PvFO5nozGVdQe3Zu/hwAEujtP/767
BCREe0fgzSvUR5Jx+na2IUhujg2lCXDghAmprrOex8+7NBGzyXzMAxGrqUliYa1gcTlSnhjFmIAp
5JY4ppV8P1oP4RukiZEbgGWcvi1UI8lyjIFdjqI+fdjeqOQYKl7GHChGGbwxPCEdtS8hTgUyEQoC
O7xpYZPPoN5N9vUH1z8TgR8FSepcSMosyrOrquZ39Jyaz/IHnou27GC4cqyA80ohKZQqBxKZ0eit
dVC1obYoNd4cyDv86ulpern6+/SFc6Lv+z5fcC1gds1N6CSBYT5SMkCWloZvfLBX1csCAA0Sz4ip
EvBOMR/rHAdZJcZ7xtdp3Hstl4Yn/plKhO4jCSZIcAed1mVq+IdUVgUGOJJzikFunNfgpC1Fx96+
KbINfe0WfJwrfTyI6AgVEhgaXb4k8dUzvPo+77kbctD3sRaZZMZ9SOnR1T0JpT4n+6BeQUUUXcs6
24eVxecW3zp5K1yG4hR7SstE0eY2qKurhyWv/0rwfuRnaMMS0MZL79ezxDYIZlVUxNkJG6lPty0V
MmO6lm7BUfHcz6wWcJEMjTEP0ku+PQqhdtrSQFCB8TXEdnZ/D536EztYGPxUEhr6SPO+dEm58g5/
UwtoParL4Pla3VOTQnFc122HxOvXMJDvem+p6DlP9zOVU7ELtAbjRV0dVi2EdcpgKBvIlhOnkAgA
VnFFevhvllN0wEwZ/j7WP2ZdtNFm4Q3B1cB/2K6DnIB6EDw+XiWJfdCsnNwoRlIubMjT1ujMi6MK
b/1ThWbIeXWFLco+nYgLct9NdKGyqdPr0+OkgDKixcHboIP2CEsFzAdEs1808o9Rnj8QxoYfKAvF
agxChfgI2in0Vn7Ugi5ZRx9wYChL9hlDw+Tw3hV7WKj1L8pfZw10K38OhLXf591kcS7LUwK8aBc4
bMzJiqhpC+brvsaZWky+0NKRrpJR72nHrHJ6/SiwAizlSrL93DRJkZ3Ohjv15adooKi7VcZPy4es
SbyoY4IeCEoikVTNO3y+0o+lME0yZpU1i6T0il7fzu4xFxAUygZx0NKwcvjWBPcfcfbi92jFs+TW
hj0ylhQo5jPdqpbHuQ+xUL5cb24fcZp9GAjtHI7zqNhDOiIvXh3EgO/NBBbo448Zk6rL7egjnOMP
SMpeBi/dq3a8aLVIgCDLp3dpoZj9b+zjxRazne8i1OolfE5fq0dPLNbDh6E2MkFiCn3GP+jtDKof
w8mvjLCgSmgjIrJQlGDOyNItUwS1+eu7AzzmsQVuVF/ivuf8EafFWZD+isrPM2CouaE5fL4ARI/V
vUCU0qGpHZalMKX6XlFCpCaFT5yBlnkp0j4qZ/RInlmvjsp8hE4DPpUAP2XYNjf6FlAQnou+bigx
eYvv6PS135Mw+DRuRWStsRtOJAlvQqSna0hUURwiLCkUNHmfc4T3+DeOXWjIdfjpmCd3/FSWvTMk
uBqZXxiAF8Ryb6xwAU5JxZ5QYClx0ssBAjtHDrMRHBj3AuB5wEhkAeX3tLWmwXzl4WTccrWB0+ON
sUdGRrlEB19nX7tJKQ==
`pragma protect end_protected
